/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

import java.time.LocalDateTime;

public class Thread {
    private int id;
    private int boardId;
    private String subject;
    private String name;
    private String email;
    private String comment;
    private String imagePath;
    private LocalDateTime createdAt;

    // Constructor for creating new threads (ID and createdAt will be generated by DB)
    public Thread(int boardId, String subject, String name, String email, String comment, String imagePath) {
        this.boardId = boardId;
        this.subject = subject;
        this.name = (name == null || name.trim().isEmpty()) ? "Anónimo" : name;
        this.email = email;
        this.comment = comment;
        this.imagePath = imagePath;
    }

    // Constructor for retrieving from DB
    public Thread(int id, int boardId, String subject, String name, String email, String comment, String imagePath, LocalDateTime createdAt) {
        this.id = id;
        this.boardId = boardId;
        this.subject = subject;
        this.name = (name == null || name.trim().isEmpty()) ? "Anónimo" : name;
        this.email = email;
        this.comment = comment;
        this.imagePath = imagePath;
        this.createdAt = createdAt;
    }

    // Getters y Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public int getBoardId() { return boardId; }
    public void setBoardId(int boardId) { this.boardId = boardId; }
    public String getSubject() { return subject; }
    public void setSubject(String subject) { this.subject = subject; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getComment() { return comment; }
    public void setComment(String comment) { this.comment = comment; }
    public String getImagePath() { return imagePath; }
    public void setImagePath(String imagePath) { this.imagePath = imagePath; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}